development:
  adapter: mysql2
  encoding: utf8
  database: tu_development
  username: root
  password:
  socket: /tmp/mysql.sock

test:
  adapter: mysql2
  encoding: utf8
  database: tu_test
  username: root
  password:
  socket: /tmp/mysql.sock


production:
  adapter: mysql2
  encoding: utf8
  database: tu_production
  username: root
  password:
  socket: /tmp/mysql.sock

