import_marks:
  cron: '0 0 1 * *'
  class: ImportMarksJob
  description: 'Importing students marks'
send_emails:
  cron: '0 0 1 * *'
  class: SendMsgToUsers
  description: 'Sends unreaded messages'
new_mark:
  cron: '0 0 1 * *'
  class: NotifiForNewMark
  description: 'Update marks'