require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe UissesController do

  # This should return the minimal set of attributes required to create a valid
  # Uiss. As you add validations to Uiss, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # UissesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all uisses as @uisses" do
      uiss = Uiss.create! valid_attributes
      get :index, {}, valid_session
      assigns(:uisses).should eq([uiss])
    end
  end

  describe "GET show" do
    it "assigns the requested uiss as @uiss" do
      uiss = Uiss.create! valid_attributes
      get :show, {:id => uiss.to_param}, valid_session
      assigns(:uiss).should eq(uiss)
    end
  end

  describe "GET new" do
    it "assigns a new uiss as @uiss" do
      get :new, {}, valid_session
      assigns(:uiss).should be_a_new(Uiss)
    end
  end

  describe "GET edit" do
    it "assigns the requested uiss as @uiss" do
      uiss = Uiss.create! valid_attributes
      get :edit, {:id => uiss.to_param}, valid_session
      assigns(:uiss).should eq(uiss)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Uiss" do
        expect {
          post :create, {:uiss => valid_attributes}, valid_session
        }.to change(Uiss, :count).by(1)
      end

      it "assigns a newly created uiss as @uiss" do
        post :create, {:uiss => valid_attributes}, valid_session
        assigns(:uiss).should be_a(Uiss)
        assigns(:uiss).should be_persisted
      end

      it "redirects to the created uiss" do
        post :create, {:uiss => valid_attributes}, valid_session
        response.should redirect_to(Uiss.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved uiss as @uiss" do
        # Trigger the behavior that occurs when invalid params are submitted
        Uiss.any_instance.stub(:save).and_return(false)
        post :create, {:uiss => {  }}, valid_session
        assigns(:uiss).should be_a_new(Uiss)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Uiss.any_instance.stub(:save).and_return(false)
        post :create, {:uiss => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested uiss" do
        uiss = Uiss.create! valid_attributes
        # Assuming there are no other uisses in the database, this
        # specifies that the Uiss created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Uiss.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => uiss.to_param, :uiss => { "these" => "params" }}, valid_session
      end

      it "assigns the requested uiss as @uiss" do
        uiss = Uiss.create! valid_attributes
        put :update, {:id => uiss.to_param, :uiss => valid_attributes}, valid_session
        assigns(:uiss).should eq(uiss)
      end

      it "redirects to the uiss" do
        uiss = Uiss.create! valid_attributes
        put :update, {:id => uiss.to_param, :uiss => valid_attributes}, valid_session
        response.should redirect_to(uiss)
      end
    end

    describe "with invalid params" do
      it "assigns the uiss as @uiss" do
        uiss = Uiss.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Uiss.any_instance.stub(:save).and_return(false)
        put :update, {:id => uiss.to_param, :uiss => {  }}, valid_session
        assigns(:uiss).should eq(uiss)
      end

      it "re-renders the 'edit' template" do
        uiss = Uiss.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Uiss.any_instance.stub(:save).and_return(false)
        put :update, {:id => uiss.to_param, :uiss => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested uiss" do
      uiss = Uiss.create! valid_attributes
      expect {
        delete :destroy, {:id => uiss.to_param}, valid_session
      }.to change(Uiss, :count).by(-1)
    end

    it "redirects to the uisses list" do
      uiss = Uiss.create! valid_attributes
      delete :destroy, {:id => uiss.to_param}, valid_session
      response.should redirect_to(uisses_url)
    end
  end

end
